stay_after_death: [example1, nightvision]
give_by_default: [nightvision]

effects:
  example1:
    commands: [/mysuper command]
    effects: [REGENERATION:1, STRENGTH:2]
    delay: 60
    perm: my.custom.permission
  nightvision:
    commands: [/nv, /nightvision, /night vision]
    effects: [NIGHTVISION:1]
    delay: 0
    perm: nightvision.permission
