give_by_default: [nightvision_example, example1]

effects:
  example1:
    commands: [/mysuper command]
    effects: [REGENERATION 1, INCREASE_DAMAGE 2]
    duration: 60
    cooldown: 300
    perm: my.custom.permission
  nightvision_example:
    commands: [/nv, /nightvision, /night vision]
    effects: [NIGHT_VISION 1]
    duration: 0
    cooldown: 10
    perm: nightvision.permission

messages:
  effect_give: "&aYou have activated effect %effect%"
  effect_disable: "&cYou disable the effect %effect%"
  effect_on_cooldown: "&cYou have to wait %time% before using again this effect"
  error_config_effect_exist: "&cERROR: the potion effect &e%potion% &cdon't exist"
  error_effect_permission: "&cYou don't have the permssion to use the effect %effect%"
  no_permission: "&cYou don't have the permission to do that"