name: BULCommandEffect
version: ${project.version}
description: ${project.description}
author: AliHaine
main: com.alihaine.bulcommandeffect.BULCommandEffect
api-version: 1.13
commands:
  bulcommandeffect:
    description: Reload config