name: BulPotionEffect
version: ${project.version}
description: ${project.description}
author: AliHaine
main: com.alihaine.bulpotioneffect.BulPotionEffect
api-version: 1.13
commands:
  bpe:
    description: Default command